### ISSUE TITLE
Accepting a buy request fails

### ISSUE THREAD

**Issue by patpedrosa** [emipasat/gooddollar#53]
**Describe the bug** When a seller receives a buy request and tries to accept it, it fails.

**To Reproduce** Steps to reproduce the behavior:

1. Go to an unpaid buy request
2. Click on Accept
3. See error

**Screenshots** 
<img width="1372" alt="Screen Shot 2022-09-05 at 09 33 52" src="https://user-images.githubusercontent.com/49105975/188453270-2aa6a468-7c3b-4437-9229-340898eb52de.png">

**Comment by BogosRobert** [comment]
Those buttons shouldn't be there. We removed them and made some changes on the texts in order for the process to be more intuitive.
