### ISSUE TITLE
Fix sale page copy

### ISSUE THREAD

**Issue by patpedrosa** [emipasat/gooddollar#55]
Sellers are getting confused by this copy, thinking that it's requesting them to pay for their own product:

"If you didn't pay yet click here or scan the QR code below"

<img width="752" alt="Screen Shot 2022-09-05 at 09 54 58" src="https://user-images.githubusercontent.com/49105975/188454670-f5711006-27a1-411e-839c-36ec89efb0cd.png">

Let's do a quick copy fix:

**ATTENTION, BUYER:** If you didn't pay yet click here or scan the QR code below.

**Comment by BogosRobert** [comment]
We removed this section from the seller view to avoid any confusion
